server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:shareit
    username: test
    password: test

#---
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
#spring.datasource.username=root
#spring.datasource.password=root
#---

